
###
# keycloak module that declares
apiVersion: install.verrazzano.io/v1beta2
kind: Platform
metadata:
  name: myvz
  namespace: default
spec:
  modules:
    - name:      keycloak
      namespace: keycloak
      values:
        - credentialSecret:  # Assumes we have a credential secret that can be defined as input to this chart
            name: verrazzano-admin  #
      # recursively declare dependencies between modules
      dependencies:
        - name: mysql  # MySQL chart that has a hard Helm dependency on mysql-operator
          values:
            - passwordSecret: verrazzano-admin  # Assumes we tell mysql where credential secret is stored


  components:
    keycloak:
      mysql:
    mysql-operator:
---

apiVersion: install.verrazzano.io/v1beta2
kind: Platform
metadata:
  name: myvz
  namespace: default
spec:
  modules:
    - name:      keycloak
      namespace: keycloak
      values:    # Optional. Supports configuration of feature.
        - credentialSecret:
            name: verrazzano-admin
      # recursively declare dependencies between modules
      dependencies:
        - name: mysql  # MySQL chart that has a hard Helm dependency on mysql-operator
          values:
            - passwordSecret: verrazzano-admin

---
# Custom Keycloak CR?